# SPDX-License-Identifier: GPL-3.0
# Copyright (c) 2025 Gavin Henry <ghenry@sentrypeer.org>

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
        # These are peer deps of Cargo and should not be automatically bumped
        - dependency-name: "semver"
        - dependency-name: "crates-io"
    rebase-strategy: "disabled"
