# SPDX-License-Identifier: MIT
# Copyright (c) 2025 Gavin Henry <ghenry@sentrypeer.org>

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install deps
      run: |
        set -x
        sudo apt-get update
        sudo echo RESET grub-efi/install_devices | sudo debconf-communicate grub-pc
        sudo apt-get -y upgrade
        sudo apt-get install \
        pkg-config \
        ninja-build -y
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
