# SPDX-License-Identifier: GPL-3.0
# Copyright (c) 2025 Gavin Henry <ghenry@sentrypeer.org>

name: Rust Clippy Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  clippy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: clippy

    - name: Install deps
      run: |
        set -x
        sudo apt-get update
        sudo echo RESET grub-efi/install_devices | sudo debconf-communicate grub-pc
        sudo apt-get -y upgrade
        sudo apt-get install \
        pkg-config \
        libgnutls-dev \
        libmsgpack-cxx-dev \
        libargon2-dev \
        libasio-dev \
        libjsoncpp-dev \
        libssl-dev \
        libfmt-dev \
        nettle-dev \
        ninja-build -y

    # For things in our bindings.rs that we don't own, i.e.
    # warning: unsafe function's docs are missing a `# Safety` section
    - name: Run clippy
      run: cargo clippy -- -D warnings -A clippy::missing_safety_doc
