# SPDX-License-Identifier: GPL-3.0
# Copyright (c) 2025 Gavin Henry <ghenry@sentrypeer.org>

name: Cargo Vet Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  vet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Install cargo-vet
        run: cargo install cargo-vet

      - name: Run cargo vet
        run: cargo vet